version: '3'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=lecabdlaexaewj
      - POSTGRES_PASSWORD=cd5f23d0bd9d1cfce58b55ebd48aedf7ceeb7949cc869018c065c86fe942d587
      - POSTGRES_DB=flash-coffee
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      # copy the sql script to create tables
      - ./migration/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      - PostgresqlUrl=postgres://lecabdlaexaewj:cd5f23d0bd9d1cfce58b55ebd48aedf7ceeb7949cc869018c065c86fe942d587@postgres:5432/d4fgafbaksfli